# Generated by Django 5.0.2 on 2025-11-22 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="devicelogin",
            options={"ordering": ["-created_at"]},
        ),
    ]
